spring:
  application:
    name: boot4-webmvc-example
springdoc:
  packages-to-scan: io.github.sbracely.extended.problem.detail.webmvc.example.controller
  paths-to-match: /mvc-extended-problem-detail/**